baseURL = 'https://antinatalismus-jetzt.netlify.app/'
languageCode = 'de-de'
title = 'Antinatalismus Jetzt.'

#theme = 'ananke'
#theme = 'quint'
theme = 'hugo-book'

## https://gohugo.io/content-management/menus/
# sectionPagesMenu = 'main'

## https://gethinode.com/
#[[module.imports]]
#path = 'github.com/gethinode/hinode'

## https://github.com/alex-shpak/hugo-book
[params]
  # (Optional, default light) Sets color theme: light, dark or auto.
  # Theme 'auto' switches between dark and light modes based on browser/os preferences
  #BookTheme = 'light'

  # (Optional, default docs) Specify section of content to render as menu
  # You can also set value to "*" to render all sections to menu
  BookSection = '*'
